### ISSUE TITLE
Bug: Copy-pasting AUR package name into search field does not work

### ISSUE THREAD

**Issue by CommanderRedYT** [Lukas-Heiligenbrunner/AURCache#15]
When copy-pasting a string into the searchfield, a empty list shows up. If you type every character manually, it works. (Removing one character and adding it again does not work either.

**Comment by Lukas-Heiligenbrunner** [comment]
Hey, 
I can't reproduce this one, what exactly are you searching? And on the AUR page right, not on the main dashboard?

**Comment by CommanderRedYT** [comment]
Yes, on the AUR page. I just copy-paste any full package name like `yay` into the field. It looks like there are two input fields ontop of each other. But it shows no results. When I enter `y` `a` `y` it works.

**Comment by Lukas-Heiligenbrunner** [comment]
https://github.com/Lukas-Heiligenbrunner/AURCache/assets/30468956/19d904c5-7159-4f27-917d-7330ee5f7ed3

Like this?

**Comment by Lukas-Heiligenbrunner** [comment]
You could also check if the request to `/api/search?query=yay` is successfull

**Comment by CupricReki** [comment]
Can't reproduce this either.

**Comment by Lukas-Heiligenbrunner** [comment]
Since @CommanderRedYT doesn't reply and I can't reproduce this I'll close the issue.
