### ISSUE TITLE
Bug: Unable to build AUR packages that depend on other AUR packages

### ISSUE THREAD

**Issue by CommanderRedYT** [Lukas-Heiligenbrunner/AURCache#16]
When trying to build a package that has another AUR package as its dependency, a error message will be printed that is saying that pacman is unable to locate the package. I assume the backend calls `pacman` directly instead some AUR helper?

**Comment by Lukas-Heiligenbrunner** [comment]
At the moment I first download the build-script from AUR and then use makepkg to build the package. 
I don't have any dependency resolution from aur for now. So you would have to install the dependencies first and then the main package for version solving to work. (Thats why I have added localhost in the repos of the container)
