### ISSUE TITLE
install a package with an unknown public key

### ISSUE THREAD

**Issue by tjaartvdwalt** [Lukas-Heiligenbrunner/AURCache#20]
Is there a way to add a public key, so that you can build a package that has an unknown key?
For example, I get the following error when trying to build dropbox.

```
==> Verifying source file signatures with gpg...
dropbox-lnx.x86_64-202.4.5551.tar.gz ... FAILED (unknown public key FC918B335044912E)
```

**Comment by Lukas-Heiligenbrunner** [comment]
Hey, I've just tired to build drobox and it builds fine on my side. weird. 
You've upgraded to the latest version that i've published ~1h ago?

**Comment by tjaartvdwalt** [comment]
Thank for the quick reply @Lukas-Heiligenbrunner 

After updating my docker image, I get a different error:

![screenshot-2024-07-23-090531](https://github.com/user-attachments/assets/76405b0b-4e00-4b6d-ab6b-11fd7da02742)

I  am deploying the container with docker-compose, using the example config given in the README.

I am not sure where to find out more detail on the error. If you can point me in the right direction, I am happy to debug further.

**Comment by tjaartvdwalt** [comment]
Thank you @Lukas-Heiligenbrunner, I have it working!

I will explain my setup, in case it benefits anyone else:

I am running Dockge in Jailmaker on a Truenas SCALE. (From their next release, SCALE will migrate from K8S to Docker, but I thought I would get a head start)

I enabled FUSE, following the instructions in this issue: https://github.com/Jip-Hop/jailmaker/issues/1

**Comment by Lukas-Heiligenbrunner** [comment]
Great that it works now!
Ah ok, thanks for the info.
