### ISSUE TITLE
Pending and enqueued builds showed as successful

### ISSUE THREAD

**Issue by CupricReki** [Lukas-Heiligenbrunner/AURCache#62]
See image. There are currently no successful builds, but 3 are shown. 1 is currently being build and 2 are enqueued.

![image](https://github.com/user-attachments/assets/d0afe7f5-0fe9-4b95-b7f2-1a7d182e47e4)

**Comment by Lukas-Heiligenbrunner** [comment]
You mean the numer on the right panel, right? 
Yes thats true. Thanks!

**Comment by CupricReki** [comment]
> You mean the numer on the right panel, right?

Correct
