### ISSUE TITLE
Postgres DB Name

### ISSUE THREAD

**Issue by ralphocdol** [Lukas-Heiligenbrunner/AURCache#84]
Currently, there's no way to use a different DB name. It would be great to have an optional `DB_NAME` environment variable like

```rs
let db_name = env::var("DB_NAME").unwrap_or_else(|_| "postgres".to_string()); // I don't know rust but something like this
format!("postgres://{db_user}:{db_pwd}@{db_host}/{db_name}?currentSchema=public");
```
https://github.com/Lukas-Heiligenbrunner/AURCache/blob/734644015c428e7be9a592c73b4c697927e2b345/backend/src/db/init.rs#L39

Thanks.

**Comment by Lukas-Heiligenbrunner** [comment]
Good idea, I'll add that!

**Comment by Lukas-Heiligenbrunner** [comment]
@ralphocdol  I'll release a new version when #74  is merged. If you need this earlier you can switch to `git` tag to have the latest changes from master.
